/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Afika.Shwashwa
 */
public class TaxCalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form TaxCalculatorFrame
     */
    public TaxCalculatorFrame() {
        initComponents();
    }

    double income;
    String Ouput;

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtIncome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnEnter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTax = new javax.swing.JLabel();
        jLabelDisplay = new javax.swing.JLabel();
        jLabelDisplayIncome = new javax.swing.JLabel();
        jLabelMonthly = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAX CALCULATOR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter your Annual Income below to calculate your annual tax obligation");

        jtxtIncome.setBackground(new java.awt.Color(255, 255, 255));
        jtxtIncome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIncomeActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  ANNUAL INCOME :");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnEnter.setText("ENTER");
        jbtnEnter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnterActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setEnabled(false);

        jLabelTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTax.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTax.setText("Tax: ");

        jLabelDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDisplay.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDisplay.setText("Your tax calculation will display here");

        jLabelDisplayIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDisplayIncome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDisplayIncome.setText("Annual income: ");

        jLabelMonthly.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMonthly.setText("Monthly tax:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDisplayIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDisplayIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabelMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDisplay)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(jtxtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fantastic Four");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void Tax_Calculator(String taxCal)
     {
         String annualIncome= jtxtIncome.getText()+taxCal;
         
         String display=jLabelDisplay.getText();
         jLabelDisplay.setText(annualIncome);
         
     }
    
    private void jtxtIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIncomeActionPerformed

    private void jbtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
         try {
        income = Double.parseDouble(jtxtIncome.getText());
        double tax = 0;
        double taxPercentage=0;
        double monthlyTax=0;
        
        if(!jtxtIncome.getText().isEmpty())
        {
            if (income <= 95750) {
                tax=0; // No tax for negative or zero income
                monthlyTax= tax/12;

            } 
            else if (income >=95751 && income <= 237100 ) {
                taxPercentage=0.18;
                tax = income * taxPercentage - 17235   ; // 18% tax rate for income up to R237,100
                monthlyTax= tax/12;
            } 
            else if (income <= 370500) {
                taxPercentage=0.26;
                tax =  (42678 + (income * taxPercentage) - 78881) ; // R42,678 plus 26% tax rate for income between R237,101 and R370,500
                monthlyTax= tax/12;
            } 
            else if (income <= 512800) {
                taxPercentage=0.31;
                tax =  (77362 + (income * taxPercentage)-132090); // R77,362 plus 31% tax rate for income between R370,501 and R512,800
                monthlyTax= tax/12;
            } 
            else if (income <= 673000) {
                taxPercentage=0.36;
                tax =  (121475 + (income * taxPercentage)-201843) ; // R121,475 plus 36% tax rate for income between R512,801 and R673,000
                monthlyTax= tax/12;
            }
            else if (income <= 857900) {
                taxPercentage=0.36;
                tax =  (179147 + (income * 0.39)-255699.04) ; // R179,147 plus 39% tax rate for income between R673,001 and R857,900
                monthlyTax= tax/12;
            } 
            else if (income <= 1817000) {
                taxPercentage=0.41;
                tax =  (251258 + (income * taxPercentage)-368975) ; // R251,258 plus 41% tax rate for income between R857,901 and R1,817,000
                monthlyTax= tax/12;
            } 
            else {
                taxPercentage=0.45;
                tax =  (644489 + (income * taxPercentage)) ; // R644,489 plus 45% tax rate for income above R1,817,000
                monthlyTax= tax/12;
            }
            taxPercentage=taxPercentage*100;
            jLabelTax.setText("Tax : "+String.valueOf(Math.round(taxPercentage))+"%");
            jLabelMonthly.setText("Monthly tax: R"+ String.valueOf(Math.round(monthlyTax)));
            jLabelDisplayIncome.setText("Your income is: R"+String.valueOf(Math.round(income)));
            jLabelDisplay.setText(" Your tax obligaion is: R"+"\n"+"\n"+String.valueOf(Math.round(tax)) +" per annum");
            jtxtIncome.setText("");
        }
         } 
         catch (NumberFormatException e) {
        // Handle the exception when the input cannot be parsed as a double
        jLabelDisplay.setText("Invalid input: " +"Enter a valid amount");
        // You can display an error message to the user or take other appropriate actions
    }
         
         
//        else{
//            
//            String selectedItem=this.jComboBox1.getSelectedItem().toString();
//            
//            if(selectedItem.equalsIgnoreCase("...."))
//            {
//                jtxtDisplay.setText("You have entered an invalid input");
//
//            }
//            else if(selectedItem.equalsIgnoreCase("R94999 or less"))
//            {
//                jtxtDisplay.setText("R0 taxable obligation");
//            }
            
            
//            else if(selectedItem.equalsIgnoreCase("R95 000 - R237 100"))
//            {
//                jtxtDisplay.setText("18% of taxable income");
//            }
//            else if(selectedItem.equalsIgnoreCase("R237 101 – R370 500"))
//            {
//                jtxtDisplay.setText("R42 678 + 26% of taxable income above R3237 100");
//            }
//            else if(selectedItem.equalsIgnoreCase("R370 501 – R512 800"))
//            {
//                jtxtDisplay.setText("R77 362 + 31% of taxable income above R370 500");
//            }            
//            else if(selectedItem.equalsIgnoreCase("R512 801 – R673 000"))
//            {
//                jtxtDisplay.setText("R121 475 + 36% of taxable income above R512 800");
//            }
//            else if(selectedItem.equalsIgnoreCase("R673 001 – R857 900"))
//            {
//                jtxtDisplay.setText("R179 147 + 39% of taxable income above R673 000");
//            }
//            else if(selectedItem.equalsIgnoreCase("R857 901 – R1 817 000"))
//            {
//                jtxtDisplay.setText("R251 258 + 41% of taxable income above R857 900");
//            }
//            else if(selectedItem.equalsIgnoreCase("R1 817 001 and above"))
//            {
//                jtxtDisplay.setText("R644 489 + 45% of taxable income above R1 817 000");
//            }
//            
//        }

    }//GEN-LAST:event_jbtnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JLabel jLabelDisplayIncome;
    private javax.swing.JLabel jLabelMonthly;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnEnter;
    private javax.swing.JTextField jtxtIncome;
    // End of variables declaration//GEN-END:variables
}
